In [9]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [2]:
#Load iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
#Split the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [4]:
#Initialize the model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [5]:
#Make predictions
y_pred = model.predict(X_test)

In [7]:
#Accuracy
accuracy = accuracy_score(y_test, y_pred)

#Precision
precision = precision_score(y_test, y_pred, average='weighted')

#Recall
recall = recall_score(y_test, y_pred, average='weighted')

#F1 score
f1 = f1_score(y_test, y_pred, average='weighted')

In [8]:
print("Accuracy", accuracy)
print("Precision", precision)
print("Recall", recall)
print("F1", f1)

Accuracy 1.0
Precision 1.0
Recall 1.0
F1 1.0


In [10]:
#Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred,)
print(conf_matrix)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [11]:
def calculate_metrics(y_true, y_pred):
    tp = np.sum((y_true == 1) & (y_pred ==1))
    tn = np.sum((y_true == 0) & (y_pred ==0))
    fp = np.sum((y_true == 0) & (y_pred ==1))
    fn = np.sum((y_true == 1) & (y_pred ==0))
    
    precision_s = tp/(tp + fp)
    recall_s = p / (tp + fn)
    f1_s = 2 * (precision_s * recall_s) / (precision_s * recall_s)
    
    return precision_s, recall_s, f1_s

In [12]:
print("Precision", precision)
print("Recall", recall)
print("F1", f1)

Precision 1.0
Recall 1.0
F1 1.0
