# Manually

In [10]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [2]:
#Example data
data = np.random.rand(100, 2)
labels = np.random.randint(0, 2, 100)

In [3]:
labels

array([1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1])

In [6]:
#Number of folds
k = 5

In [7]:
#Shuffle and split data into number of k folds
indices = np.arange(len(data))
np.random.shuffle(indices)
fold_indices = np.array_split(indices, k)

In [8]:
fold_indices

[array([31, 10, 68, 75, 34, 60, 97, 94, 77, 29, 53, 50, 90, 42, 19, 27, 13,
        11, 14, 41]),
 array([57, 43, 79, 49, 59, 45,  4, 98,  6, 48, 89, 81, 61, 35, 28, 64, 18,
        65, 88,  9]),
 array([56, 70, 93, 95, 78, 17, 38, 83, 99, 22, 55, 62, 30, 47, 26, 40,  3,
        84, 12, 71]),
 array([25, 67, 66, 46, 69, 96, 63, 20, 72, 58, 86, 39, 82, 16, 76,  0, 54,
         2, 36, 33]),
 array([24, 23, 80, 21, 73, 85, 74, 91,  1, 32, 51, 92,  5,  8, 15, 44,  7,
        37, 87, 52])]

In [9]:
#Store eval. results
evaluation_results = []

In [17]:
for i in range(k):
    print("Fold Number", i+1)
    #Split the data into train and test
    test_indices = fold_indices[i]
    train_indices = np.concatenate([fold_indices[j] for j in range(k) if j !=i])
    X_train, y_train = data[train_indices], labels[train_indices]
    X_test, y_test = data[test_indices], labels[test_indices]
    
    #Train our ML model
    model = LogisticRegression()
    
    #Fit model
    model.fit(X_train, y_train)
    
    #accuracy
    accuracy = model.score(X_test, y_test)
    
    #Append the evaluation result
    evaluation_results.append(accuracy)
    
    #Calculate mean and variance of evaluation results
    mean_accuracy = np.mean(evaluation_results)
    variance_accuracy = np.var(evaluation_results)
    
    print("Mean Accuracy", mean_accuracy)
    print("Variance Accuracy", variance_accuracy)

Fold Number 1
Mean Accuracy 0.546875
Variance Accuracy 0.003896484375
Fold Number 2
Mean Accuracy 0.5441176470588235
Variance Accuracy 0.003788927335640139
Fold Number 3
Mean Accuracy 0.5416666666666666
Variance Accuracy 0.003680555555555556
Fold Number 4
Mean Accuracy 0.5473684210526316
Variance Accuracy 0.004072022160664821
Fold Number 5
Mean Accuracy 0.55
Variance Accuracy 0.003999999999999999


# using sklearn

In [20]:
from sklearn.datasets import load_wine
from sklearn.model_selection import cross_val_score

In [21]:
#Load wine dataset
wine = load_wine()
X = wine.data
y = wine.target

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [23]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [24]:
model = LogisticRegression(max_iter=1000)

#number of folds
K =5
score = cross_val_score(model, X, y, cv=k, scoring='accuracy')

C:\Users\ramsu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ramsu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [27]:
mean_accuracy = np.mean(score)
print(f"Cross validation (k={k}) Mean Accuracy", mean_accuracy)
print("Individual Fold Score", score)

Cross validation (k=5) Mean Accuracy 0.961111111111111
Individual Fold Score [0.91666667 0.94444444 0.94444444 1.         1.        ]
