# StandardScaler

#Z = x - mean/std

In [1]:
#mean = 0, std 1 

In [ ]:

#Transform on -> Test Set
#Fit Transform -> Training Set

# Normalization

In [ ]:
#between [0, 1]
#MinMaxScaler
x' = x -min(x) / max(x) - min(x)

## Reason -> Info Leakage

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

In [5]:
#Example data
np.random.seed(42)
X = np.random.rand(100, 5)
y = np.random.randint(0, 2, size=100)

In [7]:
y

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [9]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [13]:
X_test_scaled = scaler.transform(X_test)

In [15]:
scaler.mean_

array([0.50750331, 0.5095586 , 0.46848717, 0.51091336, 0.44195027])

In [16]:
scaler.scale_

array([0.30213769, 0.30119157, 0.29318291, 0.29392269, 0.31259555])